/**
 * Writes docs/PROVISIONAL.md: every provisional car (Unlimited only) and what
 * would make it a normal record, followed by the cars still held back.
 *
 *   npm run provisional-report
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { VehicleSchema, type Vehicle } from '../src/lib/schema';
import { loadRawFiles } from './load';

const vehicles: Vehicle[] = loadRawFiles().flatMap((f) => {
  const p = VehicleSchema.safeParse(f.json);
  return p.success ? [p.data] : [];
});
const provisional = vehicles.filter((v) => v.provisional).sort((a, b) => a.displayName.localeCompare(b.displayName));
const held = (JSON.parse(readFileSync('data/held/held-cars.json', 'utf8')) as { cars: { displayName: string; missing: string }[] }).cars
  .slice()
  .sort((a, b) => a.displayName.localeCompare(b.displayName));

const cell = (s: string) => s.replace(/\|/g, '\\|').replace(/\s+/g, ' ').trim();
const lines = [
  '# Provisional and held cars',
  '',
  'Generated by `npm run provisional-report`; do not edit by hand.',
  '',
  `## Provisional (${provisional.length}): in Unlimited only, never a daily answer`,
  '',
  'These rest partly on sources below the minimum standard (databases, enthusiast sites, single',
  'articles, tested or estimated figures). See docs/DATA_GUIDE.md, "Provisional records".',
  '',
  '| Car | hp | lb | What is provisional, and what would replace it |',
  '|---|---|---|---|',
  ...provisional.map((v) => `| ${cell(v.displayName)} | ${v.powerHp.value} | ${v.weightLb.value.toLocaleString('en-US')}${v.specBasis.weightType === 'dry' ? ' (dry)' : ''} | ${cell(v.provisionalNote ?? '')} |`),
  '',
  `## Still held (${held.length}): not in the game`,
  '',
  'Full details in `data/held/held-cars.json`.',
  '',
  '| Car | What is missing |',
  '|---|---|',
  ...held.map((c) => `| ${cell(c.displayName)} | ${cell(c.missing)} |`),
  '',
];
writeFileSync('docs/PROVISIONAL.md', lines.join('\n'));
console.log(`docs/PROVISIONAL.md: ${provisional.length} provisional, ${held.length} held`);
